
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>8e16eeac-2591-4d7d-b035-a8b979073052</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Anthropic" Version="12.39.0" />
    <PackageReference Include="ClosedXML" Version="0.105.1" />
  </ItemGroup>

</Project>
